### ISSUE TITLE
Failed building wheel for idyntree

### ISSUE THREAD

**Issue by Gaoyuan-Liu** [robotology/gym-ignition#295]
Hey,
I'm using ubuntu 18.04 + python3.6. 
So I guess the python-support should be >=3.8 so I create a virtual env with 3.9.2. But when I run `pip install gym-ignition` in the virtual env, I cannot install the dependencies and got errors:

>     ----------------------------------------
>     ERROR: Failed building wheel for idyntree
>     Failed to build idyntree
>     ERROR: Could not build wheels for idyntree which use PEP 517 and cannot be installed directly

Any ideas?

Thanks!

**Comment by Seiwert** [comment]
@diegoferigo I ran into this issue as well and it wasn't immediately clear what the problem was. I would recommend adding a few more details to the README to clarify the necessity of python =>3.8. I attempted to do this with a PR but do not have access.

**Comment by diegoferigo** [comment]
The README was structured to be a distilled version of the website, where information have been centralized. The system requirements are listed in [Support Policy](https://robotology.github.io/gym-ignition/master/installation/support_policy.html).
