### ISSUE TITLE
Investigate color support in mesh files

### ISSUE THREAD

**Issue by diegoferigo** [robotology/gym-ignition#31]
As reported in https://github.com/robotology/gym-ignition/pull/4, the colors are not properly displayed in our iCub models.

Despite this rendering problem, the models are loaded correctly and both links and joints are detected.

Here below an example with `iCubGazeboV2_5`:

![ignition_gazebo](https://user-images.githubusercontent.com/469199/58696586-25906b00-8398-11e9-873e-e935955b0156.png)

**Comment by traversaro** [comment]
The graphic engine is OGRE or OGRE2 ?

**Comment by diegoferigo** [comment]
I tried both, same result. Upstream they changed the scene plugin during the past 10 days (new one is `Scene3D`) but it segfaults. Probably something is wrong in my compilation from sources of the entire suite. I tried their binaries but they are not yet updated.

**Comment by traversaro** [comment]
Which source of light do you have in your scene? If you just have environment light and no point or direction source of light, a uniform color for the meshes is actually the expected outcome of the rendering process.

**Comment by diegoferigo** [comment]
I had the same suspect as well. The new world upstream added new light elements and I tried to do the same on our worlds. The only difference is that I can see the iCub shadow:

![icub_with_sun](https://user-images.githubusercontent.com/469199/58698471-9edd8d00-839b-11e9-9678-1966bb1ff666.png)

But note that this is using the old `Scene3D` plugin.

**Comment by traversaro** [comment]
Have you tried rotating the model? If the model is in shadow w.r.t. to the only source of light, the only remaining light is indeed the diffuse one.

**Comment by diegoferigo** [comment]
Just tried, no change. Good tentative, though.

**Comment by traversaro** [comment]
Things I would try to investigate more the problem: 
* A simple cube whose visual shape is given by primitive SDF shapes, instead of an external mesh (such as https://bitbucket.org/ignitionrobotics/ign-gazebo/src/default/test/media/test_model.sdf)
* A simple cube loaded from an STL model, such as the one in https://github.com/xml3d/xml3d-stl-plugin/blob/master/examples/resources/cube.stl 
* Try the simple cube converted in dae via Blender ( [cube.dae.zip](https://github.com/robotology/gym-ignition/files/3244035/cube.dae.zip) )
* A simple collada mesh model, something like the duck in https://bitbucket.org/ignitionrobotics/ign-gazebo/src/default/test/worlds/mesh.sdf

**Comment by diegoferigo** [comment]
I wanted to give a quick shot to this problem. I tried to add the following to each visual elements of the links:

```xml
<material>
    <diffuse>1 1 1 1</diffuse>
</material>
```

And this is the result:

![out](https://user-images.githubusercontent.com/469199/70715944-a20ee980-1ceb-11ea-92b0-a6d6a1940c4b.gif)

I'm not an expert on this, but as far as I know STL files do not support defining material properties. Probably the default behavior of the gazebo renderer changed, because on Gazebo Classic the same model is properly rendered (all white with shadows, similar to the result of the gif above).

**Comment by traversaro** [comment]
So, it a nutshell in ignition-gazebo it seems that the default material for primitive shapes is different from the default material used for STL meshes. This sounds like a bug in ign-gazebo or some dependent library.

**Comment by diegoferigo** [comment]
Yes, something similar. I couldn't find the source of the problem, but I'm not yet familiar with all the rendering-related codebase of the simulator.

**Comment by diegoferigo** [comment]
We adopted the `diffuse` elements workaround, as reported in https://github.com/dic-iit/gym-ignition-models/pull/1 and particularly https://github.com/dic-iit/gym-ignition-models/pull/1/commits/4e8b9404e73917ef69b7252f07502788a6da4596.

We experienced a mesh problem also with the Panda model. The model was correctly inserted in the simulation but the visual elements were transparent. Citing @paolo-viceconte:

> I discovered that both in https://github.com/mkrizmancic/franka_gazebo and in https://github.com/cpezzato/panda_simulation the visual meshes (i.e. all the *.dae files) have the transparent tag set to A_ONE, which seems to be ok only in old versions of gazebo. One possible solution is to set it to RGB_ZERO, as detailed in http://answers.gazebosim.org/question/20068/collada-model-is-not-visible-in-gazebo-89-if-transparent-a_one/.

Closing.
