### ISSUE TITLE
Discussion on the Robot abstraction

### ISSUE THREAD

**Issue by diegoferigo** [robotology/gym-ignition#33]
Currently the Robot interface has only the support of getting and setting joint values. It is enough for the simple environments we have developed, but definitely it has to be extended. I open this issue as placeholder for the discussion about how to structure the interface.

An initial list of feature we need to have is the following:

- Joints (almost finalized)
  - [x] Position
  - [x] Velocity
  - [x] Acceleration
  - [ ] Torque
  - [x] PID
- Links
  - [ ] Pose (frame orientation + position)
- Sensors
  - [ ] IMU
  - [ ] Camera
  - [ ] F/T (not yet supported by Ignition Gazebo)
- Other
  - [ ] Floating base
  - [ ] Contact wrenches

The existing interfaces are the following: [`gympp::Robot`](https://github.com/robotology/gym-ignition/blob/master/gympp/include/gympp/Robot.h) and [`gym_ignition.base.Robot`](https://github.com/robotology/gym-ignition/blob/master/gym_ignition/base/robot.py).

Currently the robot interface is unique. Likely this is not scalable, there would be too many methods. We should think how to split it in many interfaces while maintaining consistency between python and C++.

Reminder: the python interface will switch to numpy arrays soon

**Comment by DanielePucci** [comment]
@diegoferigo joint torques may be added?

**Comment by diegoferigo** [comment]
I thought they were already in the list, of course joint torques.

**Comment by diegoferigo** [comment]
Excluding sensors, all the other abstractions have been implemented in the new ScenarI/O bindings #158. Closing.
