### ISSUE TITLE
Cannot run example panda_pick_and_place.py

### ISSUE THREAD

**Issue by nicholaspalomo** [robotology/gym-ignition#350]
I cannot run the `panda_pick_and_place.py` example.

When running:
``` python examples/panda_pick_and_place.py ```

I get the following traceback:
```
Traceback (most recent call last):
  File "examples/panda_pick_and_place.py", line 8, in <module>
    from gym_ignition.rbd import conversions
ModuleNotFoundError: No module named 'gym_ignition.rbd'
```

To reproduce:
- I went through the setup/installation instructions here: https://github.com/robotology/gym-ignition
- OS: Ubuntu 18.04.
- Python version: Python 3.6.9 (also tried with Python 3.8.10).
- I can run the cartpole example just fine.

Thanks for all your work on this project. It looks really cool!

**Comment by diegoferigo** [comment]
Hi @nicholaspalomo, thanks for opening this issue. Your Ubuntu version is not currently supported, as reported in our [Support Policy](https://robotology.github.io/gym-ignition/master/installation/support_policy.html).

Regardless, can you try to provide the output of the following commands:

```python
>>> import gym_ignition
```

```python
>>> from gym_ignition.rbd import conversions
```

```bash
sudo apt-get install tree
tree $(python -c "import gym_ignition, pathlib; print(pathlib.Path(gym_ignition.__file__).parent)")
```
