### ISSUE TITLE
Develop an example to compare Runtime classes

### ISSUE THREAD

**Issue by diegoferigo** [robotology/gym-ignition#38]
At the moment the supported runtimes are the following:

- `GazeboRuntime`
- `PyBulletRuntime` (almost ready in #40)

It would be nice comparing simple environments like the existing CartPole, or an even simpler Pendulum. Without contacts, the two physics engines behaviors should mostly match.

**Comment by diegoferigo** [comment]
We should also add a comparison with a ground truth. A possibility might be a custom runtime that directly integrates the equation of motion of the pendulum.

For a fair comparison, we should model the pendulum as a cylinder and not as a mass point as commonly done.

**Comment by diegoferigo** [comment]
Equations of the pendulum have been derived in #43.

**Comment by traversaro** [comment]
If you think that it is feasible, I would also test in the pendulum case the basic coulomb + viscous friction model used in SDF. While not properly documented in the specification (see http://sdformat.org/spec?ver=1.6&elem=joint#axis_dynamics) its precise meaning is quite shared in the community (see https://bitbucket.org/osrf/gazebo/issues/381/ode-joints-dont-support-friction-parameter#comment-12156423), but I suspect that different implementation could have subtly different behaviours.

**Comment by diegoferigo** [comment]
I already considered to extend the tests to include friction. Modifying the equations should be easy, it can be a second step though. I want to verify first that simulations are comparable in the simplest case.

**Comment by diegoferigo** [comment]
Implemented in https://github.com/robotology/gym-ignition/issues/38 in the simple case without friction.
